In [1]:

# a1c levels explanation

# avg_glucose_level < 140 is Normal
# avg_glucose_level between 140 and 200 is Prediabetes
# avg_glucose_level > 200 is diabetes

##Adding new column to categorize BMI
# BMI levels explanation

# BMI < 18.5 is Underweight
# BMI between 18.5 and 24.9 is Healthy weight
# bmi between 25.0 and 29.9 is Over weight
# bmi >= 30 is Obesity



##Binning of Numerical Variables into Categorical



In [2]:
#Libraries for Basic Data Processing
import numpy as np
import pandas as pd
        
#Libraries for Exception Handling
import warnings
warnings.filterwarnings('ignore')

#Libraries for data pre-processing, visualization and analysis
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import matplotlib

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree
from sklearn.cluster import KMeans

In [3]:
data = pd.read_csv('healthcare-dataset-stroke-data.csv')
print(f"Shape Of The Dataset : {data.shape}")
print(f"Dataset Information :\n")
print(data.info())

print(f"\nGlimpse Of The Dataset :")
data.head(10)


Shape Of The Dataset : (5110, 11)
Dataset Information :

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             5110 non-null   object 
 1   age                5110 non-null   float64
 2   hypertension       5110 non-null   int64  
 3   heart_disease      5110 non-null   int64  
 4   ever_married       5110 non-null   object 
 5   work_type          5110 non-null   object 
 6   Residence_type     5110 non-null   object 
 7   avg_glucose_level  5110 non-null   float64
 8   bmi                4909 non-null   float64
 9   smoking_status     5110 non-null   object 
 10  stroke             5110 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 439.3+ KB
None

Glimpse Of The Dataset :


gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1  Female  61.0             0              0          Yes  Self-employed   
2    Male  80.0             0              1          Yes        Private   
3  Female  49.0             0              0          Yes        Private   
4  Female  79.0             1              0          Yes  Self-employed   
5    Male  81.0             0              0          Yes        Private   
6    Male  74.0             1              1          Yes        Private   
7  Female  69.0             0              0           No        Private   
8  Female  59.0             0              0          Yes        Private   
9  Female  78.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             202.21   NaN     never smoked       1  
2          Rural             105.92  32.5     never smoked       1  
3          Urban             171.23  34.4           smokes       1  
4          Rural             174.12  24.0     never smoked       1  
5          Urban             186.21  29.0  formerly smoked       1  
6          Rural              70.09  27.4     never smoked       1  
7          Urban              94.39  22.8     never smoked       1  
8          Rural              76.15   NaN          Unknown       1  
9          Urban              58.57  24.2          Unknown       1

In [4]:
print(f"\nDescription of Data (numerical data typed features only) :")
data.describe()


Description of Data (numerical data typed features only) :


age  hypertension  heart_disease  avg_glucose_level  \
count  5110.000000   5110.000000    5110.000000        5110.000000   
mean     43.226614      0.097456       0.054012         106.147677   
std      22.612647      0.296607       0.226063          45.283560   
min       0.080000      0.000000       0.000000          55.120000   
25%      25.000000      0.000000       0.000000          77.245000   
50%      45.000000      0.000000       0.000000          91.885000   
75%      61.000000      0.000000       0.000000         114.090000   
max      82.000000      1.000000       1.000000         271.740000   

               bmi       stroke  
count  4909.000000  5110.000000  
mean     28.893237     0.048728  
std       7.854067     0.215320  
min      10.300000     0.000000  
25%      23.500000     0.000000  
50%      28.100000     0.000000  
75%      33.100000     0.000000  
max      97.600000     1.000000

In [5]:
print(f"\nDescription of Data (categorical data typed features) :")
data.describe(include=object)


Description of Data (categorical data typed features) :


gender ever_married work_type Residence_type smoking_status
count     5110         5110      5110           5110           5110
unique       3            2         5              2              4
top     Female          Yes   Private          Urban   never smoked
freq      2994         3353      2925           2596           1892

In [6]:
# #Identifying and Dropping Unnecessary Columns and Duplicated Records
# data = data.drop(['id'], axis=1)

# dup = data[data.duplicated()].shape[0]
# print(f"There is {dup} duplicate entry among {data.shape[0]} entries in this dataset.")

# data.drop_duplicates(keep='first',inplace=True)
# print(f"After removing duplicate entries there are {data.shape[0]} entries in this dataset.")

In [7]:
#Identifying NULL valued attributes in dataset
print(f"Identifying Null values of the Dataset :")
data.isna().sum().to_frame()

Identifying Null values of the Dataset :


0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                201
smoking_status       0
stroke               0

In [8]:
#Imputing Missing/NA Values in dataset using Attribute Mean/Median
data['bmi'].fillna(np.round(data['bmi'].median(), 1), inplace = True) ##replaced NA values in BMI attr with Median

#Printing top 5 rows to check consistency of data
data.head(5)
print(f"After imputing Null values of the Dataset :")
data.isna().sum().to_frame()

After imputing Null values of the Dataset :


0
gender             0
age                0
hypertension       0
heart_disease      0
ever_married       0
work_type          0
Residence_type     0
avg_glucose_level  0
bmi                0
smoking_status     0
stroke             0

In [9]:
##Removed rows  where "Age= Other"
data['age'] = data['age'].astype('int')
data = data[data['gender'] != 'Other']

In [10]:
data

gender  age  hypertension  heart_disease ever_married      work_type  \
0       Male   67             0              1          Yes        Private   
1     Female   61             0              0          Yes  Self-employed   
2       Male   80             0              1          Yes        Private   
3     Female   49             0              0          Yes        Private   
4     Female   79             1              0          Yes  Self-employed   
...      ...  ...           ...            ...          ...            ...   
5105  Female   80             1              0          Yes        Private   
5106  Female   81             0              0          Yes  Self-employed   
5107  Female   35             0              0          Yes  Self-employed   
5108    Male   51             0              0          Yes        Private   
5109  Female   44             0              0          Yes       Govt_job   

     Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0             Urban             228.69  36.6  formerly smoked       1  
1             Rural             202.21  28.1     never smoked       1  
2             Rural             105.92  32.5     never smoked       1  
3             Urban             171.23  34.4           smokes       1  
4             Rural             174.12  24.0     never smoked       1  
...             ...                ...   ...              ...     ...  
5105          Urban              83.75  28.1     never smoked       0  
5106          Urban             125.20  40.0     never smoked       0  
5107          Rural              82.99  30.6     never smoked       0  
5108          Rural             166.29  25.6  formerly smoked       0  
5109          Urban              85.28  26.2          Unknown       0  

[5109 rows x 11 columns]

In [29]:
data['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked'],
      dtype=object)

In [27]:
data['bmi'].max()

97.6

In [12]:
#Preparing X & Y data, and the train - test split
## A test set of 30% of dataset is assumed for this model development
x=data.drop(['stroke'], axis=1)
y=data['stroke']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state= 124)


In [13]:
numerical_variables = ['age', 'hypertension', 'heart_disease','avg_glucose_level','bmi']
categorical_variables = ['gender','ever_married','work_type','Residence_type','smoking_status']

In [14]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

numerical_pipeline = Pipeline([('impute_missing', SimpleImputer( strategy = 'median')),
                              ('standardize_num', StandardScaler())])

In [15]:
from sklearn.preprocessing import OneHotEncoder

categorical_pipeline = Pipeline([('impute_missing_cats', SimpleImputer( strategy = 'most_frequent')),
                               ('create_dummies_cats', OneHotEncoder(handle_unknown = 'ignore', drop = 'first'))])

In [16]:
#https://github.com/appliedecon/data602-lectures/blob/main/sklearn-pipeline-example/credit.ipynb
from sklearn.compose import ColumnTransformer

categorical_pipeline_processing = ColumnTransformer( transformers = [('create_dummies', categorical_pipeline, categorical_variables)])


In [17]:
# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler.fit_transform
categorical_pipeline_processing.fit_transform(x_train, y_train)


array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [18]:
# insert code here
#https://github.com/appliedecon/data602-lectures/blob/main/sklearn-pipeline-example/credit.ipynb
processing_pipeline = ColumnTransformer(transformers=[('proc_numeric', numerical_pipeline, numerical_variables), 
                                                      ('create_dummies', categorical_pipeline, categorical_variables)])


In [19]:
#https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler.fit_transform
processing_pipeline.fit_transform(x_train, y_train)

array([[-0.89262826, -0.3304257 , -0.24339619, ...,  0.        ,
         1.        ,  0.        ],
       [-0.05725775, -0.3304257 , -0.24339619, ...,  1.        ,
         0.        ,  0.        ],
       [-1.33229696, -0.3304257 , -0.24339619, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 1.21778146, -0.3304257 , -0.24339619, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.43761581,  3.026399  , -0.24339619, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.29447721, -0.3304257 , -0.24339619, ...,  0.        ,
         0.        ,  0.        ]])

In [20]:
print(f'Training examples: {x_train.shape[0]}')
print(f'Test examples: {x_test.shape[0]}')


Training examples: 3576
Test examples: 1533


In [21]:
#Decision Tree Classifier
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
dct_clf = DecisionTreeClassifier(criterion = 'entropy',max_depth=2)

pipeline_modeling = Pipeline([('data_processing', processing_pipeline), ('tree', dct_clf)])

param_grid = [
{'tree__max_depth': [2, 5, 10, 15, 20],
'tree__min_samples_split':[3, 5, 10, 20, 40],
'tree__min_samples_leaf': [2, 5],
'tree__class_weight':[None, 'balanced']
}]

gcv_results = GridSearchCV(estimator=pipeline_modeling, param_grid=param_grid, scoring='recall', refit=True)
gcv_results = gcv_results.fit(x_train, y_train)
gcv_results.best_estimator_


#pipeline_modeling.fit(x_train,y_train)


y_pred = gcv_results.predict(x_test)
print("Test Accuracy: {} \n".format(accuracy_score(y_test, y_pred)))

print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))

print("Classification Report: \n", classification_report(y_test, y_pred))

Test Accuracy: 0.5844748858447488 

Confusion Matrix: 
 [[835 630]
 [  7  61]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.99      0.57      0.72      1465
           1       0.09      0.90      0.16        68

    accuracy                           0.58      1533
   macro avg       0.54      0.73      0.44      1533
weighted avg       0.95      0.58      0.70      1533



In [22]:
print(y_pred)

[1 0 1 ... 0 1 1]


In [23]:
df_predict_live = pd.DataFrame([['Female', 61, 0, 0, 'Yes','Self-employed','Rural',float(202.21),float(28.1),'never smoked']],columns=x_train.columns)
            
predict_y_live=gcv_results.best_estimator_.predict(df_predict_live)
print(predict_y_live[0])

1


In [25]:
x_train.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status'],
      dtype='object')

In [24]:
import pickle
pickle.dump(gcv_results.best_estimator_, open('projpredictgcv.pkl', 'wb'))